#!MC 1400
# Created by Tecplot 360 build 14.0.2.35002
$!VarSet |MFBD| = 'C:\Users\1234\Documents'
$!Varset |NUMlOOP|=0
$!LOOP 70
$!VarSet |num|=(0+0.2*|NUMLOOP|)
$!GLOBALTHREED SLICE{ORIGIN{X = |num|}}
$!CREATESLICEZONEFROMPLANE 
  SLICESOURCE = VOLUMEZONES
  FORCEEXTRACTIONTOSINGLEZONE = YES
  COPYCELLCENTEREDVALUES = NO
$!VarSet |NUMLOOP|+=1
$!ENDLOOP
$!RemoveVar |MFBD|
